version: "3.8"

services:
  abja-postgres:
    container_name: abja-postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  abja-kino-back:
    container_name: abja-kino-back
    build: ./abja_kino_back
    environment:
      # Spring
      SPRING_DATASOURCE_URL: jdbc:postgresql://abja-postgres:5432/${POSTGRES_DATABASE}
      SPRING_ADMIN_USERNAME: ${SPRING_ADMIN_USERNAME}
      SPRING_ADMIN_PASSWORD: ${SPRING_ADMIN_PASSWORD}
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}

      # Postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    depends_on:
      - abja-postgres
    ports:
      - "8080:8080"

  abja-kino-front:
    container_name: abja-kino-front
    build: ./abja_kino_front
    environment:
      - API_URL=${API_URL:-http://abja-kino-back:8080}
    ports:
      - "8081:8081"
    depends_on:
      - abja-kino-back
    


volumes:
  postgres-data:


networks:
  default:
    name: abja-kino-network
